### ISSUE TITLE
Disk Size

### ISSUE THREAD

**Issue by CarlWebster** [RMITBLOG/Win11Compat#2]
Disk Size: 1890.3603477478 Reports as error

![w11](https://user-images.githubusercontent.com/7387263/123662933-87339580-d7fb-11eb-9ee7-acc0162652c5.png)

**Comment by RMITBLOG** [comment]
Thanks, Carl. Will look into this. Also, there is a newer version in releases. https://github.com/RMITBLOG/Win11Compat/releases

**Comment by RMITBLOG** [comment]
Checked and fixed in version 1.2 release 

https://github.com/RMITBLOG/Win11Compat/releases/tag/1.2
